services:

  postgres:
    image: postgres:17
    container_name: tomoor-postgres

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./Tomoor-CafeAPI

    container_name: tomoor-api

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    volumes:
      - uploads_data:/app/uploads

  ui:
    build:
      context: ./Tomoor-CafeUI

    container_name: tomoor-ui

    restart: unless-stopped

    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}

    ports:
      - "5173:5173"

    depends_on:
      - api

volumes:
  postgres_data:
  uploads_data:
